mqtt:
  client-id: itsADevClient
  ip: 127.0.0.1
  port: 1883
  qos: 0
  subscribe:
    - tcp
    - pc
    - light
    - door
    - projector

logging:
  level:
    com.fall.handler: debug

plc:
  list:
    # 所有pc
    - name: allDevice
      ip: 192.168.3.45
      port: 6000
      poweron-command: [ "openall" ]
      poweroff-command: [ "closeall" ]

    # 研发管线
    - name: pipeline
      ip: 192.168.3.45
      port: 6000
      poweron-command: [ "openyfgx" ]
      poweroff-command: [ "closeyfgx" ]

    # 合作院企
    - name: cooperation
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openhzyq" ]
      poweroff-command: [ "closehzyq" ]

    # 儿童呼吸消化
    - name: respiration
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openethxxh" ]
      poweroff-command: [ "closeethxxh" ]

    # 儿童神经
    - name: neuron
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openetsj" ]
      poweroff-command: [ "closeetsj" ]

    # 体重管理
    - name: weight
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "opentzgl" ]
      poweroff-command: [ "closetzgl" ]

    # 足脊健康
    - name: feet
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openzjjk" ]
      poweroff-command: [ "closezjjk" ]

    # 女性健康
    - name: female
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "opennxjk" ]
      poweroff-command: [ "closenxjk" ]

    # 皮科医美
    - name: skin
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openpkym" ]
      poweroff-command: [ "closepkym" ]

    # 肿瘤
    - name: tumor
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openzl" ]
      poweroff-command: [ "closezl" ]

    # 内分泌 & 风湿免疫
    - name: immunity
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "opennfmfs" ]
      poweroff-command: [ "closenfmfs" ]

    # 生长激素
    - name: growth
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openszjs" ]
      poweroff-command: [ "closeszjs" ]

    # 生产基地
    - name: production
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openscjd" ]
      poweroff-command: [ "closescjd" ]

    # 发展战略 (投影仪主机)
    - name: projector
      ip: 192.168.3.45
      is-hex: true
      port: 6000
      poweron-command: [ "openfzzl" ]
      poweroff-command: [ "closefzzl" ]
      sub-command-list:
        - name: projectorPoweron
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "3030504F4EOD" ]
        - name: projectorPoweroff
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "3030504F460D" ]
        - name: play
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 01 FE" ]
        - name: pause
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 02 FE" ]
        - name: volumeUp
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA E3 0A FE" ]
        - name: volumeDown
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA E4 0A FE" ]
        - name: head
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 0B FE" ]
        - name: last
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 0F FE" ]
        - name: next
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 10 FE" ]
        - name: mute
          ip: 192.168.3.45
          is-hex: true
          port: 6000
          command: [ "FF AA CC 0A FE" ]


    # 企业荣誉
    - name: honor
      ip: 192.168.x.x
      port: 6000
      poweron-command: [ "openqyry" ]
      poweroff-command: [ "closeqyry" ]

    # 门禁1
    - name: door1
      ip: 192.168.x.x
      port: 6000
      reversal-command: [ "door01" ]

    # 门禁2
    - name: door2
      ip: 192.168.x.x
      port: 6000
      reversal-command: [ "door02" ]

    # 灯带
    - name: light
      ip: 192.168.3.45
      port: 6000
      sub-command-list:
        - name: all
          ip: 192.168.3.45
          port: 6000
          address: ["192.168.3.48:6000"]
          command: [ "reversalall" ]
        - name: 1
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal01" ]
        - name: 2
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal02" ]
        - name: 3
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal03" ]
        - name: 4
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal04" ]
        - name: 5
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal05" ]
        - name: 6
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal06" ]
        - name: 7
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal07" ]
        - name: 8
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal08" ]
        - name: 9
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal09" ]
        - name: 10
          ip: 192.168.3.45
          port: 6000
          command: [ "reversal10" ]